ManejoPresupuesto/Models/PaginacionViewModel.cs
namespace ManejoPresupuesto.Models
{
    public class PaginacionViewModel
    {
        public int Pagina { get; set; } = 1;
        private int recordsPorPagina = 10;
        private readonly int cantidadMaximaRecordPorPagina = 50;
        public int RecordsPorPagina
        {
            get { return recordsPorPagina; }
            set { recordsPorPagina = (value > cantidadMaximaRecordPorPagina) ? cantidadMaximaRecordPorPagina : value; }
        }
        public int RecordsAsaltar => recordsPorPagina * (Pagina - 1);
    }
}

ManejoPresupuesto/Models/ResumenMontosViewModel.cs
namespace ManejoPresupuesto.Models
{
    public class ResumenMontosViewModel
    {
        public decimal Ingresos { get; set; }
        public decimal Gastos { get; set; }
        public decimal Total { get; set; }
    }
}

ManejoPresupuesto/Models/reporteTransaccionesDetalladas.cs
namespace ManejoPresupuesto.Models
{
    public class reporteTransaccionesDetalladas
    {
        public DateTime FechaInicio { get; set; }
        public DateTime FechaFin { get; set; }
        public IEnumerable<TransaccionesPorFecha> TransaccionesObtenidos { get; set; }
        public decimal BalancesDepositos => TransaccionesObtenidos.Sum(x => x.BalancesDepositos);
        public decimal BalancesRetiros => TransaccionesObtenidos.Sum(x => x.BalancesRetiros);
        public decimal Total => BalancesDepositos - BalancesRetiros;
        public class TransaccionesPorFecha 
        {

            public DateTime FechaTransaccion { get; set; }
            public IEnumerable<Transaccion> Transacciones { get; set; }

            public decimal BalancesDepositos => Transacciones.Where(x => x.TipoOperacionId == TipoOperacion.Ingresos).Sum(x => x.Monto);
            public decimal BalancesRetiros => Transacciones.Where(x => x.TipoOperacionId == TipoOperacion.Gastos).Sum(x => x.Monto);
        }


    }
}

ManejoPresupuesto/Controllers/CuentaController.cs
using AutoMapper;
using ManejoPresupuesto.Models;
using ManejoPresupuesto.Servicios;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ManejoPresupuesto.Controllers
{
    public class CuentaController:Controller
    {
        private readonly IRepositorioTiposCuentas repositorioTiposCuentas;
        private readonly IServicioUsuario servicioUsuario;
        private readonly IRepositorioCuenta repositorioCuenta;
        private readonly IMapper mapper;

      private readonly IRepositorioTransacciones repositorioTransacciones;
        private readonly IServicioReportes servicioReportes;

        //private readonly IMapper mapper;
        //private readonly IRepositorioTransaccion repositorioTransaccion;

        public CuentaController(IRepositorioTiposCuentas repositorioTiposCuentas, IServicioUsuario servicioUsuario,IRepositorioCuenta repositorioCuenta,IMapper mapper,IRepositorioTransacciones repositorioTransacciones,IServicioReportes servicioReportes)
        {
            this.repositorioTiposCuentas = repositorioTiposCuentas;
            this.servicioUsuario = servicioUsuario;
            this.repositorioCuenta = repositorioCuenta;
            this.mapper = mapper;
            this.repositorioTransacciones = repositorioTransacciones;
            this.servicioReportes = servicioReportes;
            //this.mapper = mapper;
            //this.repositorioTransaccion = repositorioTransaccion;
        }
        [HttpGet]
        public async Task<IActionResult> Crear()
        {
            var usuarioId = servicioUsuario.obtenerUsuarioId();
            //var tipoCuenta = await repositorioCuenta.obtener(usuarioId);
            var modelo = new CuentaCreacionViewModel();
            modelo.tipocuenta =await ObtenerTipoCuenta(usuarioId);
            return View(modelo);
        }
        [HttpPost]
        public async Task<IActionResult> Crear(CuentaCreacionViewModel cuenta)
        {
            var usuarioId = servicioUsuario.obtenerUsuarioId();
            var TipoCuenta = await repositorioTiposCuentas.ObtenerPorId(cuenta.TipoCuentaId,usuarioId);
            if(TipoCuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            if (!ModelState.IsValid)
            {
                cuenta.tipocuenta = await ObtenerTipoCuenta(usuarioId);
                return View(cuenta);
            }

            await repositorioCuenta.Crear(cuenta);
            return RedirectToAction("Index");

        }

        public async Task<IEnumerable<SelectListItem>>ObtenerTipoCuenta(int usuarioId)
        {
            var tiposCuenta = await repositorioTiposCuentas.Obtener(usuarioId);
            return tiposCuenta.Select(x => new SelectListItem(x.Nombre, x.Id.ToString()));
        }


        public async Task<IActionResult> Index()
        {
            var usuarioId = servicioUsuario.obtenerUsuarioId();
            var cuentaporTipoCuenta = await repositorioCuenta.Buscar(usuarioId);

            var modelo = cuentaporTipoCuenta
                .GroupBy(x => x.TipoCuenta)
                .Select(grupo => new IndiceCuentaViewModel
            {
                  TipoCuenta = grupo.Key,
                  cuentas = grupo.AsEnumerable()

            }).ToList();

            return View(modelo);
        }
        public async Task<IActionResult> Editar(int id)
        {
            var usuarioId = servicioUsuario.obtenerUsuarioId();
            var cuenta = await repositorioCuenta.ObtenerPorId(id,usuarioId);
            if (cuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            //var modelo = mapper.Map<CuentaCreacionViewModel>(cuenta);
            var modelo = mapper.Map<CuentaCreacionViewModel>(cuenta);
            modelo.tipocuenta = await ObtenerTipoCuenta(usuarioId);
            return View(modelo);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(CuentaCreacionViewModel obtenerid) 
        {
            var usuarioId = servicioUsuario.obtenerUsuarioId();
            var validarCuenta = await repositorioCuenta.ObtenerPorId(obtenerid.Id, usuarioId);
            if (validarCuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            var ValidarTipoCuenta = await repositorioTiposCuentas.ObtenerPorId(obtenerid.TipoCuentaId, usuarioId);
            if(validarCuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            await repositorioCuenta.Actualizar(obtenerid);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Borrar(int id)
        {
            var UsuarioId = servicioUsuario.obtenerUsuarioId();
            var Cuenta = await repositorioCuenta.ObtenerPorId(id, UsuarioId);
            if(Cuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }
            return View(Cuenta);
        }

        [HttpPost]
        public async Task<IActionResult> BorrarCuenta(int id)
        {
            var UsuarioId = servicioUsuario.obtenerUsuarioId();
            var Cuenta = await repositorioCuenta.ObtenerPorId(id, UsuarioId);
            if (Cuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }
            await repositorioCuenta.Borrar(id);
            return RedirectToAction("Index");
        }


        //public async Task<IActionResult> Borrar(int id)
        //{
        //    var usuarioId = servicioUsuario.obtenerUsuarioId();
        //    var cuenta = await repositorioCuenta.ObtenerPorId(usuarioId, id);
        //    if(cuenta is null)
        //    {
        //        return RedirectToAction("NoEncontrado", "Home");
        //    }

        //    return View(cuenta);
        //}

        
        public async Task<IActionResult>Detalle(int id,int mes,int año)
        {
            var usuarioId = servicioUsuario.obtenerUsuarioId();
            var cuenta = await repositorioCuenta.ObtenerPorId(id, usuarioId);
            if(cuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }
            ViewBag.cuenta = cuenta.Nombre;
            var modelo = await servicioReportes.obtenerReporteTransaccionesDetalladasPorCuenta(usuarioId, id, mes, año,ViewBag);
            return View(modelo);
        }




        //public async Task<IActionResult> Detalle (int id, int mes, int año)
        //{
        //    var usuarioId = servicioUsuario.obtenerUsuarioId();
        //    var cuentas = await repositorioCuenta.ObtenerPorId(id, usuarioId);
        //    if(cuentas is null)
        //    {
        //        return RedirectToAction("NoEncontrado", "Home");
        //    }

        //    DateTime fechaInicio;
        //    DateTime fechaFin;
        //    if(mes <= 0 || mes > 12 || año <= 1900)
        //    {
        //        var hoy = DateTime.Today;
        //        fechaInicio = new DateTime(hoy.Year, hoy.Month, 1);
        //    }
        //    else
        //    {
        //        fechaInicio = new DateTime(año, mes, 1);
        //    }

        //    fechaFin = fechaInicio.AddMonths(1).AddDays(-1);
        //    var cuentaPorTransaccion = new ObtenerTransaccionPorCuenta()
        //    {
        //        cuentasId = id,
        //        usuarioId = usuarioId,
        //        fechaInicio = fechaInicio,
        //        fechaFin = fechaFin
        //    };

        //    var transacciones = await repositorioTransaccion.obtenerPorCuentaId(cuentaPorTransaccion);
        //    var modelo = new ReporteTransaccionesDetalladas();
        //    ViewBag.cuenta = cuentas.nombre;
        //    var transaccionesPorFecha = transacciones.OrderByDescending(x => x.fechatransaccion)
        //        .GroupBy(x => x.fechatransaccion)
        //        .Select(grupo => new ReporteTransaccionesDetalladas.TransaccionesPorFecha()
        //        {
        //            FechaTransaccion = grupo.Key,
        //            transacciones = grupo.AsEnumerable()
        //        });

        //    modelo.TransaccionesAgrupadas = transaccionesPorFecha;
        //    modelo.FechaInicio = fechaInicio;
        //    modelo.FechaFin = fechaFin;
        //    ViewBag.mesAnterior = fechaInicio.AddMonths(-1).Month;
        //    ViewBag.añoAnterior = fechaInicio.AddMonths(-1).Year;
        //    ViewBag.mesPosterior = fechaInicio.AddMonths(1).Month;
        //    ViewBag.añoPosterior = fechaInicio.AddMonths(1).Year;

        //    ViewBag.retornourl = HttpContext.Request.Path + HttpContext.Request.QueryString;

        //    return View(modelo);
        //}
    }

    
}

ManejoPresupuesto/Controllers/UsuariosController.cs
using ManejoPresupuesto.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ManejoPresupuesto.Controllers
{
    public class UsuariosController:Controller
    {
        private readonly UserManager<Usuario> userManager;
        private readonly SignInManager<Usuario> signInManager;

        public UsuariosController(UserManager<Usuario> userManager,SignInManager<Usuario> signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
        }
        [AllowAnonymous]
        public IActionResult Registro()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Registro(UsuariosViewModel modelo) 
        {
            if (!ModelState.IsValid)
            {
                return View(modelo);
            }

            var usuario = new Usuario() { Email = modelo.Email };
            var resultado = await userManager.CreateAsync(usuario,password:modelo.Password);

            if (resultado.Succeeded)
            {
                await signInManager.SignInAsync(usuario, isPersistent: true);
                return RedirectToAction("Index", "Transaccion");
            }
            else
            {
                foreach(var error in resultado.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }

                return View(modelo);
            }

            
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login (LoginViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var resultado = await signInManager.PasswordSignInAsync(model.Email, model.Password, model.Recuerdame, lockoutOnFailure: false);
            if (resultado.Succeeded)
            {
                return RedirectToAction("Index", "Transaccion");
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Nombre del usuario o password incorrecto");
                return View(model);
            }


        }

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(IdentityConstants.ApplicationScheme);
            return RedirectToAction("Index", "Transaccion");
        }
    }
}

ManejoPresupuesto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ManejoPresupuesto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ManejoPresupuesto.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Custom.css"/>
    <link rel="stylesheet" href="ManejoPresupuesto.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/lib/fullCalendar/main.min.css"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Transaccion" asp-action="Index">ManejoPresupuesto</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark"  asp-controller="Transaccion" asp-action="Index">Transacciones</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark"  asp-controller="Cuenta" asp-action="Index">Cuenta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"  asp-controller="TiposCuentas" asp-action="Index">Tipos Cuentas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"  asp-controller="Categoria" asp-action="Index">Categoria</a>
                        </li>
                    </ul>
                    <partial name="_LinksLogin"/>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ManejoPresupuesto - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-ui/jquery-ui.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ManejoPresupuesto/Views/Shared/_LinksLogin.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<Usuario> signInManager
<ul class="navbar-nav">
    @if (signInManager.IsSignedIn(User))
    {
        <li class="nav-item">
            <span class="nav-link text-dark">Hola, @User.Identity.Name</span>
        </li>
        <li class="nav-item">
            <form class="from-inline" asp-action="Logout" asp-controller="Usuarios">
                <button type="submit" class="nav-link btn btn-link text-dark">
                    Logout
                </button>
            </form>
        </li>
    }else
    {
        <li class="nav-item">
            <a class="nav-link dark-text" asp-controller="Usuarios" asp-action="Registro"> Registro </a>
        </li>
        <li class="nav-item">
            <a class="nav-link dark-text" asp-controller="Usuarios" asp-action="Login"> Login </a>
        </li>
    }

</ul>

ManejoPresupuesto/Views/Shared/_NavegarPorMeses.cshtml
@model DateTime
<h4>
    
    <a asp-route-mes="@ViewBag.mesAnterior" asp-route-año="@ViewBag.añoAnterior" class="btn btn-secondary"><i class="bi-chevron-left"></i></a>
    @Model.ToString("MMM") - @Model.Year
    <a asp-route-mes="@ViewBag.mesPosterior" asp-route-año="@ViewBag.añoPosterior" class="btn btn-secondary"><i class="bi-chevron-right"></i></a>

</h4>

ManejoPresupuesto/Views/Shared/_Paginacion.cshtml
@model PaginacionRespuesta;
@{
    var plantillaLinks = string.Concat(Model.BaseURL, "?pagina={0}&recordsPorPagina={1}");
    var activarBotonAnterior = Model.Pagina > 1;
    var activarBotonSiguiente = Model.Pagina < Model.CantidadTotalDePagina;
}
<nav>
    <ul class="pagination">
        <li class="page-item @(activarBotonAnterior ? null:"disabled")">
            @if (activarBotonAnterior)
            {
                <a class="page-link" href="@string.Format(plantillaLinks,Model.Pagina - 1,Model.RecordsPorPaginas)">Anterior</a>
            }
            else
            {
                <span class="page-link">Anterior</span>
            }
        </li>


        @for (var pagina = 1; pagina <= Model.CantidadTotalDePagina; pagina++)
        {
            <li class="page-item @(pagina == Model.Pagina? "active":null)">
                <a class="page-link" href="@string.Format(plantillaLinks,pagina,Model.RecordsPorPaginas)">@pagina</a>
            </li>
        }

        <li class="page-item @(activarBotonSiguiente ? null:"disabled")">
            @if (activarBotonSiguiente)
            {
                <a class="page-link" href="@string.Format(plantillaLinks,Model.Pagina + 1,Model.RecordsPorPaginas)">Siguiente</a>
            }
            else
            {
                <span class="page-link">Siguiente</span>
            }
        </li>

    </ul>
</nav>

ManejoPresupuesto/Views/Shared/_ReporteTransaccionesDetalladas.cshtml
@model reporteTransaccionesDetalladas
@{
    var ResumenMontos = new ResumenMontosViewModel()
    {
        Ingresos = Model.BalancesDepositos,
        Gastos = Model.BalancesRetiros,
        Total = Model.Total
    };
}
<partial name="_NavegarPorMeses" model="@Model.FechaInicio"/>
<partial name="_ResumenMontos" model="@ResumenMontos"/>
@if(Model.TransaccionesObtenidos.Count() == 0){
    <h3>No Hay nada para mostrar</h3>
}else{
    <table class="table">
        <tbody>
            @foreach (var transaccionAgrupada in Model.TransaccionesObtenidos)
            {
                <tr style="background-color:lightblue;font-size:26px">
                    <td colspan="3">
                        @transaccionAgrupada.FechaTransaccion.Day
                        <span class="badge bg-secondary">@transaccionAgrupada.FechaTransaccion.ToString("ddd")</span>
                    </td>
                    <td class="Activo">@transaccionAgrupada.BalancesDepositos.ToString("N")</td>
                    <td class="Pasivo">@transaccionAgrupada.BalancesRetiros.ToString("N")</td>
                </tr>
                @foreach (var transaccion in transaccionAgrupada.Transacciones)
                {
                  <tr style="vertical-align:middle">
                      <td>
                          <a asp-controller="Transaccion" asp-route-UrlRetorno="@ViewBag.UrlRetorno" asp-action="Editar" asp-route-id="@transaccion.Id"><i class="bi-pencil"></i></a>
                      </td>
                      <td>@transaccion.categoria</td>
                      <td>@transaccion.cuenta</td>
                      <td class="Activo">@(transaccion.TipoOperacionId==TipoOperacion.Ingresos ? transaccion.Monto.ToString("N") : null)</td>
                      <td class="Pasivo">@(transaccion.TipoOperacionId==TipoOperacion.Gastos? transaccion.Monto.ToString("N") : null)</td>
                  </tr>
                }
            }
            
        </tbody>
    </table>
}

ManejoPresupuesto/Views/Shared/_ResumenMontos.cshtml
@model ResumenMontosViewModel

<div class="contenedor-totales mb-3">
    <div>
        <div>
            <strong>Depositos</strong>
        </div>
        <div class="Activo">
            @Model.Ingresos.ToString("N")
        </div>
    </div>
    <div>
        <div>
            <strong>Retiros</strong>
        </div>
        <div class="Pasivo">
            @Model.Gastos.ToString("N")
        </div>
    </div>
    <div>
        <div>
            <strong>Totales</strong>
        </div>
        <div>
            @Model.Total.ToString("N")
        </div>
    </div>
</div>